// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7CrgfhBlh2QqkkXK1fZy_EkT_QI4qj4',
    appId: '1:954036644445:web:157463ad1d131b2c5bbbb4',
    messagingSenderId: '954036644445',
    projectId: 'planning-poker-87b21',
    authDomain: 'planning-poker-87b21.firebaseapp.com',
    storageBucket: 'planning-poker-87b21.firebasestorage.app',
    measurementId: 'G-ZXX2GP0T0L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA23PafTyULPGicxfK8yIUrQbefJVk9JBQ',
    appId: '1:954036644445:ios:be1ab00290a897e65bbbb4',
    messagingSenderId: '954036644445',
    projectId: 'planning-poker-87b21',
    storageBucket: 'planning-poker-87b21.firebasestorage.app',
    iosBundleId: 'com.example.planningPoker',
  );
}
